[workspace]
resolver = "2"

# This wildcard pattern automatically finds ANY folder starting with 'chapter_'
# No more manual editing. No more dead links.
members = [
    "chapter_*",
    "quest_*"
]
exclude = [
    "frontend"
]